In [1]:
import pandas
import numpy
from matplotlib import pyplot
import seaborn

from PIL import Image

In [2]:
catdogs = pandas.read_csv("catdogs.csv")

catdogs

,ID,TYPE,PATH,ORIGINAL_PATH
0,0,Cat,../../catdogs/Cat_0.png,../../Cat/0.jpg
1,1,Cat,../../catdogs/Cat_1.png,../../Cat/1.jpg
2,2,Cat,../../catdogs/Cat_2.png,../../Cat/2.jpg
3,3,Cat,../../catdogs/Cat_3.png,../../Cat/3.jpg
4,4,Cat,../../catdogs/Cat_4.png,../../Cat/4.jpg
...,...,...,...,...
24993,12495,Dog,../../catdogs/Dog_12495.png,../../Dog/12495.jpg
24994,12496,Dog,../../catdogs/Dog_12496.png,../../Dog/12496.jpg
24995,12497,Dog,../../catdogs/Dog_12497.png,../../Dog/12497.jpg
24996,12498,Dog,../../catdogs/Dog_12498.png,../../Dog/12498.jpg


In [52]:
catdogs["PATH"]

0            ../../catdogs/Cat_0.png
1            ../../catdogs/Cat_1.png
2            ../../catdogs/Cat_2.png
3            ../../catdogs/Cat_3.png
4            ../../catdogs/Cat_4.png
                    ...             
24993    ../../catdogs/Dog_12495.png
24994    ../../catdogs/Dog_12496.png
24995    ../../catdogs/Dog_12497.png
24996    ../../catdogs/Dog_12498.png
24997    ../../catdogs/Dog_12499.png
Name: PATH, Length: 24998, dtype: object

In [53]:
X = numpy.vstack(
    catdogs["PATH"].apply(
        lambda path: numpy.ascontiguousarray(Image.open(path).convert("L")).reshape(64 * 64))
        .apply(lambda x: (255 - x) / 255).values)

X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [54]:
catdogs["TYPE"]

0        Cat
1        Cat
2        Cat
3        Cat
4        Cat
        ... 
24993    Dog
24994    Dog
24995    Dog
24996    Dog
24997    Dog
Name: TYPE, Length: 24998, dtype: object

In [9]:
y1 = (catdogs["TYPE"] == "Cat").astype(int)
y2 = (catdogs["TYPE"] == "Dog").astype(int)

Y = pandas.DataFrame({
    "y1": y1,
    "y2": y2,
})

Y

,y1,y2
0,1,0
1,1,0
2,1,0
3,1,0
4,1,0
...,...,...
24993,0,1
24994,0,1
24995,0,1
24996,0,1


In [56]:
! pip install scikit-learn


[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: pip install --upgrade pip


In [57]:
from sklearn.model_selection import train_test_split

Xa, Xb, Ya, Yb = train_test_split(X, Y, test_size=3000, random_state=123)

In [58]:
Xa

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [59]:
import keras

modelo = keras.Sequential([
    keras.Input(shape=(64 * 64,)),
    keras.layers.Dense(128, activation="relu"),
    keras.layers.Dense(128, activation="relu"),
    keras.layers.Dense(2, activation="sigmoid"),
])

modelo.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                 │ (None, 128)            │       524,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 128)            │        16,512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 2)              │           258 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 541,186 (2.06 MB)

 Trainable params: 541,186 (2.06 MB)

 Non-trainable params: 0 (0.00 B)

In [60]:
modelo.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

In [61]:
historial = modelo.fit(Xa, Ya, epochs=100)

Epoch 1/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 4s 5ms/step - accuracy: 0.5505 - loss: 0.7021
Epoch 2/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.5779 - loss: 0.6784
Epoch 3/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.5937 - loss: 0.6692
Epoch 4/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.5942 - loss: 0.6677
Epoch 5/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6078 - loss: 0.6595
Epoch 6/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6076 - loss: 0.6595
Epoch 7/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6022 - loss: 0.6622
Epoch 8/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6124 - loss: 0.6551
Epoch 9/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6113 - loss: 0.6570
Epoch 10/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6107 - loss: 0.6582
Epoch 11/100
688/688 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.6110 - loss: 0.6578
Epoch 12/100
688/688 ━━━━━━━━━━━━━━━━━━━━

In [63]:
modelo.evaluate(Xb, Yb)

94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6061 - loss: 0.6933


[0.6997601985931396, 0.5973333120346069]

## Entrenamiento con una Red Neuronal Convolucional

In [4]:
import keras

modelo = keras.Sequential([
    keras.Input(shape=(64, 64, 1)),
    keras.layers.Conv2D(32, 5, strides=2, activation="relu"),
    keras.layers.Conv2D(32, 3, strides=2, activation="relu"),
    keras.layers.MaxPool2D(5),
    keras.layers.Flatten(),
    keras.layers.Dense(2, activation="sigmoid"),
])

modelo.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 30, 30, 32)     │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 14, 14, 32)     │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 2, 2, 32)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 2)              │           258 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 10,338 (40.38 KB)

 Trainable params: 10,338 (40.38 KB)

 Non-trainable params: 0 (0.00 B)

In [5]:
modelo.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

In [6]:
X = numpy.vstack(
    catdogs["PATH"].apply(
        lambda path: numpy.ascontiguousarray(Image.open(path).convert("L")).reshape(64, 64, 1))
        .apply(lambda x: (255 - x) / 255).values).reshape(len(catdogs["PATH"]), 64, 64, 1)

X

array([[[[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        ...,

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]]],


       [[[0.        ],
         [0.        ],
         [0.  

In [7]:
X.shape

(24998, 64, 64, 1)

In [10]:
from sklearn.model_selection import train_test_split

Xa, Xb, Ya, Yb = train_test_split(X, Y, test_size=3000, random_state=123)

In [11]:
historial = modelo.fit(Xa, Ya, epochs=35)

Epoch 1/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 6s 7ms/step - accuracy: 0.5612 - loss: 0.6799
Epoch 2/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.6493 - loss: 0.6294
Epoch 3/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 6s 9ms/step - accuracy: 0.6771 - loss: 0.6017
Epoch 4/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.6960 - loss: 0.5823
Epoch 5/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7025 - loss: 0.5702
Epoch 6/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.7161 - loss: 0.5569
Epoch 7/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7225 - loss: 0.5456
Epoch 8/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.7279 - loss: 0.5394
Epoch 9/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.7347 - loss: 0.5315
Epoch 10/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 6s 8ms/step - accuracy: 0.7384 - loss: 0.5239
Epoch 11/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.7467 - loss: 0.5180
Epoch 12/35
688/688 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step

In [13]:
modelo.evaluate(Xb, Yb)

94/94 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7362 - loss: 0.5132


[0.5342577695846558, 0.7323333621025085]

In [12]:
modelo.save("cnn_32_32_64x64x1_35e.keras")